/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedGarageRouteImport } from './routes/_authenticated/garage'
import { Route as AuthenticatedGalaxyGalaxyIdRouteImport } from './routes/_authenticated/galaxy.$galaxyId'
import { Route as AuthenticatedLessonGalaxyIdStarIdRouteImport } from './routes/_authenticated/lesson.$galaxyId.$starId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGarageRoute = AuthenticatedGarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGalaxyGalaxyIdRoute =
  AuthenticatedGalaxyGalaxyIdRouteImport.update({
    id: '/galaxy/$galaxyId',
    path: '/galaxy/$galaxyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonGalaxyIdStarIdRoute =
  AuthenticatedLessonGalaxyIdStarIdRouteImport.update({
    id: '/lesson/$galaxyId/$starId',
    path: '/lesson/$galaxyId/$starId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/generate': typeof GenerateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/garage': typeof AuthenticatedGarageRoute
  '/galaxy/$galaxyId': typeof AuthenticatedGalaxyGalaxyIdRoute
  '/lesson/$galaxyId/$starId': typeof AuthenticatedLessonGalaxyIdStarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/generate': typeof GenerateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/garage': typeof AuthenticatedGarageRoute
  '/galaxy/$galaxyId': typeof AuthenticatedGalaxyGalaxyIdRoute
  '/lesson/$galaxyId/$starId': typeof AuthenticatedLessonGalaxyIdStarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/generate': typeof GenerateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/garage': typeof AuthenticatedGarageRoute
  '/_authenticated/galaxy/$galaxyId': typeof AuthenticatedGalaxyGalaxyIdRoute
  '/_authenticated/lesson/$galaxyId/$starId': typeof AuthenticatedLessonGalaxyIdStarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/generate'
    | '/sitemap.xml'
    | '/garage'
    | '/galaxy/$galaxyId'
    | '/lesson/$galaxyId/$starId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/generate'
    | '/sitemap.xml'
    | '/garage'
    | '/galaxy/$galaxyId'
    | '/lesson/$galaxyId/$starId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/generate'
    | '/sitemap.xml'
    | '/_authenticated/garage'
    | '/_authenticated/galaxy/$galaxyId'
    | '/_authenticated/lesson/$galaxyId/$starId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  GenerateRoute: typeof GenerateRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/garage': {
      id: '/_authenticated/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof AuthenticatedGarageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/galaxy/$galaxyId': {
      id: '/_authenticated/galaxy/$galaxyId'
      path: '/galaxy/$galaxyId'
      fullPath: '/galaxy/$galaxyId'
      preLoaderRoute: typeof AuthenticatedGalaxyGalaxyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lesson/$galaxyId/$starId': {
      id: '/_authenticated/lesson/$galaxyId/$starId'
      path: '/lesson/$galaxyId/$starId'
      fullPath: '/lesson/$galaxyId/$starId'
      preLoaderRoute: typeof AuthenticatedLessonGalaxyIdStarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGarageRoute: typeof AuthenticatedGarageRoute
  AuthenticatedGalaxyGalaxyIdRoute: typeof AuthenticatedGalaxyGalaxyIdRoute
  AuthenticatedLessonGalaxyIdStarIdRoute: typeof AuthenticatedLessonGalaxyIdStarIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGarageRoute: AuthenticatedGarageRoute,
  AuthenticatedGalaxyGalaxyIdRoute: AuthenticatedGalaxyGalaxyIdRoute,
  AuthenticatedLessonGalaxyIdStarIdRoute:
    AuthenticatedLessonGalaxyIdStarIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  GenerateRoute: GenerateRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
